[package]
name = "fluido-core"
version = "0.0.0"
edition = "2021"

[dependencies]
fluido-generation = { path = "../fluido-generation/" }
fluido-ir = { path = "../fluido-ir" }
fluido-parse = { path = "../fluido-parse" }
fluido-types = { path = "../fluido-types" }
thiserror = "1.0.57"
