[workspace]
resolver = "2"
members = ["fluido-generation", "fluido", "fluido-parse", "fluido-ir", "fluido-core", "fluido-types"]

[workspace.dependencies]
anyhow = "1.0.79"
egg = "0.9.5"
petgraph = "0.6.4"
thiserror = "1.0.57"
