[package]
name = "fluido"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true } 
clap = { workspace = true, features = ["derive"] }
fluido-core = { path = "../fluido-core/" }
fluido-types = { path = "../fluido-types/" }
