[package]
name = "fluido-types"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
egg = { workspace = true }
thiserror = { workspace = true } 
serde = { workspace = true, features = ["derive"] }
